#!/bin/bash
# 2011-04-15  Michele Tavella <michele.tavella@epfl.ch>

if [ "z$1" == "z" ]; then
	echo "[cl_screenloop] DEVICE";
	exit 1;
fi

if [ ! -f $HOME/.screenrc-cnbitk ]; then
	echo "bind 's' screen -t Shell bash" \
		>> $HOME/.screenrc-cnbitk
	echo "hardstatus alwayslastline" \
		>> $HOME/.screenrc-cnbitk
	echo "hardstatus string '%{kw}%-w%{RW} %n %t %{kw}%+w %='" \
		>> $HOME/.screenrc-cnbitk
	echo "caption always "\
		>> $HOME/.screenrc-cnbitk
	echo "caption '%{wk} CnbiTk ScreenLoop %= %h  %l  %Y.%m.%d  %c%a %{wk}'" \
		>> $HOME/.screenrc-cnbitk
	echo "shelltitle '$ |idle'" >> $HOME/.screenrc-cnbitk
fi

CHECK=`screen -ls | grep cnbitk | awk '{print $1}'`;

if [ "z$CHECK" == "z" ]; then
	echo "[cl_screenloop] Check passed";
	cl_rpcnotify "CnbiTk ScreenLoop" "Connecting to $1"
else
	echo "[cl_screenloop] Error: a cnbitk screen is already attached: $CHECK";
	cl_rpcnotify "CnbiTk ScreenLoop" "GNU Screen already attached: $CHECK";
	exit 2;
fi

ACQUISITION="cl_acquisition -d $1";

echo "[cl_screenloop] Starting screen session"
screen -d -m -S cnbitk -t "RPC Shell" bash

echo "[cl_screenloop] Attaching cl_nameserver"
screen -S cnbitk -dr -X screen -t "Nameserver" "cl_nameserver"

sleep 5
echo "[cl_screenloop] Attaching cl_processing"
screen -S cnbitk -dr -X screen -t "Processing" "cl_processing"

echo "[cl_screenloop] Attaching cl_acquisition"
screen -S cnbitk -dr -X screen -t "Acquisition" $ACQUISITION

echo "[cl_screenloop] Attaching cl_tidmonitor"
screen -S cnbitk -dr -X screen -t "TiD Monitor" "cl_tidmonitor"

CHECK=`screen -ls | grep cnbitk | awk '{print $1}'`;
cl_rpcnotify "CnbiTk ScreenLoop" "GNU Screen attached: $CHECK";

exit 0;
