#!/bin/bash
# 2011-10-01  Michele Tavella <michele.tavella@epfl.ch>

LOG_FILE="/etc/cnbitk/cclogger.xsl"
LOG_LINK="/tmp/cnbitk-$USER/cclogger.xsl"
if [ -e $LOG_FILE ]; then
	if [ -e $LOG_LINK ]; then
		exit 2;
	else
		cp $LOG_FILE $LOG_LINK;
		exit 0;
	fi
fi

exit 1;
