#!/bin/bash
# 2011-05-27  Michele Tavella <michele.tavella@epfl.ch>
# 2011-05-17  Inaki Iturrate <inaki.iturrate@epfl.ch>

if [ "z$1" == "z" ]; then
	echo "[cl_develloop] Error: cl_acquisition arguments needed";
	exit 1;
fi

cl_rpcnotify "CnbiTk cl_develloop" "Starting: $*"

gnome-terminal \
---tab "CnbiTk RPC Shell (devel)" \
---tab -e "bash -c 'cl_keepalive cl_nameserver'" --title "CnbiTk Nameserver (devel)" \
---tab -e "bash -c 'sleep 2; cl_keepalive cl_processing'" --title "CnbiTk Processing (devel)" \
---tab -e "bash -c 'sleep 4; cl_keepalive cl_acquisition $*'" --title "CnbiTk Acquisition (devel)" \
---tab -e "bash -c 'sleep 6; cl_keepalive cl_ndfmonitor -p /pipe15'" --title "CnbiTk NDF Monitor (devel)" \
---tab -e "bash -c 'sleep 6; cl_keepalive cl_tidmonitor'" --title "CnbiTk TiD Monitor (devel)" \
---tab -e "bash -c 'sleep 6; cl_keepalive cl_ticmonitor'" --title "CnbiTk TiC Monitor (devel)"

cl_rpcnotify "CnbiTk cl_develloop" "Stopped"
