#!/bin/bash
# 2011-05-27  Michele Tavella <michele.tavella@epfl.ch>
# 2011-05-17  Inaki Iturrate <inaki.iturrate@epfl.ch>

if [ "z$1" == "z" ]; then
	echo "[cl_debugloop] Error: cl_acquisition arguments needed";
	exit 1;
fi

cl_rpcnotify "CnbiTk cl_debugloop" "Starting: $*"

gnome-terminal \
---tab -e "bash -c 'cl_keeprunning cl_nameserver'" --title "CnbiTk Nameserver (debug, keeprunning)" \
---tab -e "bash -c 'sleep 2; cl_keeprunning cl_processing'" --title "CnbiTk Processing (debug, keeprunning)" \
---tab -e "bash -c 'sleep 4; cl_keeprunning cl_acquisition $*'" --title "CnbiTk Acquisition (debug, keeprunning)" \
---tab -e "bash -c 'sleep 6; cl_keepalive cl_ndfmonitor -p /pipe15'" --title "CnbiTk NDF Monitor (debug, keepalive)" \
---tab -e "bash -c 'sleep 6; cl_keepalive cl_tidmonitor'" --title "CnbiTk TiD Monitor (debug, keepalive)" \
---tab -e "bash -c 'sleep 6; cl_keepalive lc_eventcheck -p /pipe16'" --title "CnbiTk Event Check (debug, keepalive)" \
---tab -e "bash -c 'sleep 6; cl_keepalive cl_tidsender -u'" --title "CnbiTk TiD Sender (debug, keepalive)"

cl_rpcnotify "CnbiTk cl_debugloop" "Stopped"
