#!/bin/bash
# 2011-05-27  Michele Tavella <michele.tavella@epfl.ch>

if [ "z$1" == "z" ]; then
	echo "Usage: cp_keeprunning COMMAND [OPTION ...]";
	exit 1;
fi

echo "[cp_keeprunning] Running '$@'";
while true; do
	reset
	$@;
	stty echo
	echo ""
	echo "[cp_keeprunning] Terminated at `date`";
	sleep 5;
done
