#!/usr/bin/env python
# 2011-04-14  Michele Tavella <michele.tavella@epfl.ch>

import pygtk
pygtk.require('2.0')
import pynotify
import sys

def main(argv=None):
    if not pynotify.init("Basics"):
        sys.exit(1)
    if not pynotify.init("Urgency"):
        sys.exit(1)

    if argv is None:
         argv = sys.argv

    n = pynotify.Notification(sys.argv[1], sys.argv[2])
    n.set_urgency(pynotify.URGENCY_NORMAL)
    n.set_timeout(1000)

    if not n.show():
        print "Failed to send notification"
        sys.exit(1)

if __name__ == "__main__":
	main()
