# 2011-01-22  Michele Tavella <michele.tavella@epfl.ch>

local-install:
	@mkdir -p ${CNBITKMAT_ROOT}/mtpath/
	@cp -vf *.m ${CNBITKMAT_ROOT}/mtpath/

install:
	@mkdir -p /opt/cnbitkmat/mtpath/
	@cp -vf *.m /opt/cnbitkmat/mtpath/
