# 2011-01-22  Michele Tavella <michele.tavella@epfl.ch>

local-install:
	@mkdir -p ${CNBITK_MATLAB}/mtpath/
	@cp -vf *.mex* ${CNBITK_MATLAB}/mtpath/
	@cp -vf ndf_*.m ${CNBITK_MATLAB}/mtpath/
	@cp -vf printf.m ${CNBITK_MATLAB}/mtpath/

install:
	@mkdir -p /opt/cnbitkmat/mtpath/
	@cp -vf *.mex* /opt/cnbitkmat/mtpath/
	@cp -vf ndf_*.m /opt/cnbitkmat/mtpath/
	@cp -vf printf.m /opt/cnbitkmat/mtpath/
