# 2011-01-22  Michele Tavella <michele.tavella@epfl.ch>

local-install:
	@mkdir -p ${CNBITKMAT_ROOT}/mtpath/
	@cp -vf *.mex* ${CNBITKMAT_ROOT}/mtpath/
	@cp -vf ndf_*.m ${CNBITKMAT_ROOT}/mtpath/
	@cp -vf printf.m ${CNBITKMAT_ROOT}/mtpath/

install:
	@mkdir -p /opt/cnbitkmat/mtpath/
	@cp -vf *.mex* /opt/cnbitkmat/mtpath/
	@cp -vf ndf_*.m /opt/cnbitkmat/mtpath/
	@cp -vf printf.m /opt/cnbitkmat/mtpath/
